//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/ControlMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMap"",
    ""maps"": [
        {
            ""name"": ""PlayerMovement"",
            ""id"": ""91029e4f-bc84-4b65-8731-b05cac3f60f3"",
            ""actions"": [
                {
                    ""name"": ""CameraLook"",
                    ""type"": ""Value"",
                    ""id"": ""e27c19d7-37be-493e-8073-0197f5fbab2b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraLookMouse"",
                    ""type"": ""Value"",
                    ""id"": ""32c739c8-cfbb-4420-8bc1-589d4143870a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LockMouse"",
                    ""type"": ""Button"",
                    ""id"": ""f9304449-188b-40f7-b699-a2216524a565"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerMove"",
                    ""type"": ""Value"",
                    ""id"": ""d4ebc9b5-2670-4b4a-827a-ca061ea1e7ca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RunModifier"",
                    ""type"": ""Button"",
                    ""id"": ""729d9b62-c7f7-4a2d-a67c-1263e624216c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RunToggle"",
                    ""type"": ""Button"",
                    ""id"": ""73f14ec8-119f-40d3-b495-35918103faf3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CrawlModifier"",
                    ""type"": ""Button"",
                    ""id"": ""713eb9f2-91ac-4bbc-a4e4-64a681765dd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CrawlToggle"",
                    ""type"": ""Button"",
                    ""id"": ""4e1be39a-6fbf-469a-9969-ed18f494b72d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraLookVR"",
                    ""type"": ""Value"",
                    ""id"": ""9078b690-8235-4119-abf6-f9d9266136bf"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMoveVR"",
                    ""type"": ""Value"",
                    ""id"": ""2ddba0fd-bfab-4ec7-aa24-e17e12184cd2"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetVR"",
                    ""type"": ""Button"",
                    ""id"": ""8b3c2d1a-b4d9-49c5-8978-17c1cc80db81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHandPosVR"",
                    ""type"": ""Value"",
                    ""id"": ""f3ec05e0-0839-48fe-b82f-a52ef6fb2641"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightHandRotVR"",
                    ""type"": ""Value"",
                    ""id"": ""b74b41be-2444-40ae-b4fb-42062fb62fdc"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftHandPosVR"",
                    ""type"": ""Value"",
                    ""id"": ""8b629ac0-618e-41e6-b6ff-7b03a1f319f9"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftHandRotVR"",
                    ""type"": ""Value"",
                    ""id"": ""4c4c1589-9405-4ea7-9849-d03a48c34b1f"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FireGun"",
                    ""type"": ""Button"",
                    ""id"": ""c67b5671-577c-4d0a-9756-2031684f3abe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceFlag"",
                    ""type"": ""Button"",
                    ""id"": ""18071498-615c-4aab-83ef-ef5d7f54b216"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceWall"",
                    ""type"": ""Button"",
                    ""id"": ""1684d6dc-10a4-4454-bbb3-e9bddc273c74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EscapeMonster"",
                    ""type"": ""Button"",
                    ""id"": ""52aec281-1552-4517-a794-3daf45c1e940"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6c268517-9a09-4d79-a9bb-71f3feaebf36"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone,ScaleVector2(x=15)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d3e8e0f5-d098-49ed-955d-38a05441ea83"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=8)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9c7a196f-c26f-4697-9a22-2a79b9f3b150"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""530a58f5-992c-4c81-af0d-7ee8de33db8a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""558fb414-8d18-43be-b797-ae9d8e7d4c45"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone,ScaleVector2(x=10)"",
                    ""groups"": """",
                    ""action"": ""CameraLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""065c62b6-bc9c-4fc3-b542-c4f73bbf3a30"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""412161e8-3e1c-48ca-9c5f-b5c877c0935e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone,ScaleVector2(x=1.571429,y=1.571429)"",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7883f529-3e65-4dfa-924d-2324e75e2c1f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=1.571429,y=1.571429)"",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""86d0f013-c62a-4fd9-8880-63ed502690c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1221964a-930d-48fa-b7b5-be4907db5262"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a6e59df1-4aa0-4f7f-aa62-605ea7e7c359"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a375c9a3-f3a0-4faf-bf91-42acc0dc3ec0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e3d263d-0dfa-405d-ba8d-689f024ff881"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbc0b170-f9bc-4fab-9e43-556f6d9e8e36"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ffbc605-f0c0-4d2f-a40e-dcc4e83efc03"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""203fcef2-6971-4a1e-92d8-b87543bc0d83"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d3e123b-1109-426c-a036-20ec1aa926e4"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrawlModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b099303-c479-4817-9c5b-df271a23ec53"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrawlToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a01a130b-faa5-466d-bda0-3257b48fab9e"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrawlToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d301033-f6d1-4bfe-98f0-8940b0bc5870"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=1.571429,y=1.571429)"",
                    ""groups"": """",
                    ""action"": ""CameraLookMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d55c0c-338f-4484-afa0-ec9d82bbc7e7"",
                    ""path"": ""<XRInputV1::OpenXR::HeadTrackingOpenXR>/devicerotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLookVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f91be0d0-5b69-49ea-bdfb-aac1784b4854"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CrawlModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d651e030-dd91-4358-a139-1e17f6e22665"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a970b2f-e7ea-4cf4-ad01-ddd93bcbd982"",
                    ""path"": ""<XRHMD>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69f4dc5b-45e5-4b1c-9d77-690fb3ec09fc"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ba6cdd8-f21e-4462-b605-786f0d3d313d"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHandPosVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cd72573-a1c5-4a34-bece-3d3cf3639e39"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHandRotVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c06d6c28-5649-4039-9974-6da7a2c7dce1"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandPosVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e3d146f-62f3-4a60-b51b-bd85c18c59a6"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandRotVR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e2d31b3-c4c6-49b6-89b0-e6219dffaf63"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d61030ce-62b4-4ac4-b13d-dc70e4242791"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e78c7c32-c7e1-466a-8c11-9222882617c4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19b23fc2-c21e-40b9-9d6a-b186430025a7"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7342c64d-69c9-420e-9c46-73118393e16b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceFlag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d899153-5405-481c-a719-a118fbbd83cc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceFlag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70a6d13c-3c9e-4cb8-ab7b-c4de66599a50"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceFlag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cabf8f82-79dc-4083-b296-c763ecb2ff51"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d5cc149-ea5f-423b-9958-2c632da6ebb8"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5332a207-b266-4fea-8752-f0b6caa7550b"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cb69f5d-422e-4016-b5e1-e5c0063cf799"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeMonster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""564bdd95-8499-4ce1-afed-29ee90a2d24b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeMonster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6708636-d584-47c7-8e79-79d0eb60c43b"",
                    ""path"": ""<XRController>/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeMonster"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LevelControl"",
            ""id"": ""cd54e05c-f6c1-45be-96ae-a8b6a5f47544"",
            ""actions"": [
                {
                    ""name"": ""NextLevel"",
                    ""type"": ""Button"",
                    ""id"": ""9fd9e279-ef00-45f1-a3ae-13afd8ac8797"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PreviousLevel"",
                    ""type"": ""Button"",
                    ""id"": ""1a4aace4-f8c7-401f-b8a5-176a332d26c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""7128655e-b057-4bf6-82ea-915cff2c2d86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnlockMouse"",
                    ""type"": ""Button"",
                    ""id"": ""e6affbae-2b9f-427a-8ed9-2802ec678fde"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""26e7986e-627f-40f3-8dfa-4615fcdbf79c"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc060b20-5961-451c-9d97-2154b1c031f4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebccb5a7-24eb-46be-b8f1-133d4d202ec1"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23ba230e-5f2f-4ae5-8a3d-a18c44329b18"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18230b70-b8d2-4a40-b018-c47aec6211f7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10196660-7428-4c3b-813f-f6f679118c44"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""861ff81e-bbb0-4dea-a8bd-532069062b8d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97898dd4-1af6-4677-907b-cb54bd295e81"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dfcdbc9-457c-4a5f-baea-df18a8885887"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7065a613-fcc9-4c4e-95d7-4ece766ead46"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnlockMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIControl"",
            ""id"": ""1aa381c5-33f4-4a70-a323-413874329fb4"",
            ""actions"": [
                {
                    ""name"": ""ToggleCompass"",
                    ""type"": ""Button"",
                    ""id"": ""3dbe4266-213e-42cd-aaec-f4315450d900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleStats"",
                    ""type"": ""Button"",
                    ""id"": ""986cc776-10d9-4e9f-8b44-3d6cd57dd651"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMap"",
                    ""type"": ""Button"",
                    ""id"": ""1fd8f07f-662d-45e9-a9ff-d9be67fb66ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8b327de3-c997-4dcb-b1b4-edc29d1a28c2"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCompass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e22219d5-3d9e-468d-9f2f-f1bd95f64f0c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCompass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dac387e9-a368-4073-809f-e75856bdc622"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCompass"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8f4e427-0ab2-48e9-8088-7f00fd48c128"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f597da76-e846-4160-addb-9851d63a40c8"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8263b441-744b-4e8f-9f86-73f589f5aaad"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aabb72ec-1a33-49e4-a94f-f0b801ab394b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92179eff-20c9-433b-a800-688fb02554ed"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7452bf0-a030-43e0-9a18-3fa7aca0966d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMovement
        m_PlayerMovement = asset.FindActionMap("PlayerMovement", throwIfNotFound: true);
        m_PlayerMovement_CameraLook = m_PlayerMovement.FindAction("CameraLook", throwIfNotFound: true);
        m_PlayerMovement_CameraLookMouse = m_PlayerMovement.FindAction("CameraLookMouse", throwIfNotFound: true);
        m_PlayerMovement_LockMouse = m_PlayerMovement.FindAction("LockMouse", throwIfNotFound: true);
        m_PlayerMovement_PlayerMove = m_PlayerMovement.FindAction("PlayerMove", throwIfNotFound: true);
        m_PlayerMovement_RunModifier = m_PlayerMovement.FindAction("RunModifier", throwIfNotFound: true);
        m_PlayerMovement_RunToggle = m_PlayerMovement.FindAction("RunToggle", throwIfNotFound: true);
        m_PlayerMovement_CrawlModifier = m_PlayerMovement.FindAction("CrawlModifier", throwIfNotFound: true);
        m_PlayerMovement_CrawlToggle = m_PlayerMovement.FindAction("CrawlToggle", throwIfNotFound: true);
        m_PlayerMovement_CameraLookVR = m_PlayerMovement.FindAction("CameraLookVR", throwIfNotFound: true);
        m_PlayerMovement_CameraMoveVR = m_PlayerMovement.FindAction("CameraMoveVR", throwIfNotFound: true);
        m_PlayerMovement_ResetVR = m_PlayerMovement.FindAction("ResetVR", throwIfNotFound: true);
        m_PlayerMovement_RightHandPosVR = m_PlayerMovement.FindAction("RightHandPosVR", throwIfNotFound: true);
        m_PlayerMovement_RightHandRotVR = m_PlayerMovement.FindAction("RightHandRotVR", throwIfNotFound: true);
        m_PlayerMovement_LeftHandPosVR = m_PlayerMovement.FindAction("LeftHandPosVR", throwIfNotFound: true);
        m_PlayerMovement_LeftHandRotVR = m_PlayerMovement.FindAction("LeftHandRotVR", throwIfNotFound: true);
        m_PlayerMovement_FireGun = m_PlayerMovement.FindAction("FireGun", throwIfNotFound: true);
        m_PlayerMovement_PlaceFlag = m_PlayerMovement.FindAction("PlaceFlag", throwIfNotFound: true);
        m_PlayerMovement_PlaceWall = m_PlayerMovement.FindAction("PlaceWall", throwIfNotFound: true);
        m_PlayerMovement_EscapeMonster = m_PlayerMovement.FindAction("EscapeMonster", throwIfNotFound: true);
        // LevelControl
        m_LevelControl = asset.FindActionMap("LevelControl", throwIfNotFound: true);
        m_LevelControl_NextLevel = m_LevelControl.FindAction("NextLevel", throwIfNotFound: true);
        m_LevelControl_PreviousLevel = m_LevelControl.FindAction("PreviousLevel", throwIfNotFound: true);
        m_LevelControl_Pause = m_LevelControl.FindAction("Pause", throwIfNotFound: true);
        m_LevelControl_UnlockMouse = m_LevelControl.FindAction("UnlockMouse", throwIfNotFound: true);
        // UIControl
        m_UIControl = asset.FindActionMap("UIControl", throwIfNotFound: true);
        m_UIControl_ToggleCompass = m_UIControl.FindAction("ToggleCompass", throwIfNotFound: true);
        m_UIControl_ToggleStats = m_UIControl.FindAction("ToggleStats", throwIfNotFound: true);
        m_UIControl_ToggleMap = m_UIControl.FindAction("ToggleMap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMovement
    private readonly InputActionMap m_PlayerMovement;
    private List<IPlayerMovementActions> m_PlayerMovementActionsCallbackInterfaces = new List<IPlayerMovementActions>();
    private readonly InputAction m_PlayerMovement_CameraLook;
    private readonly InputAction m_PlayerMovement_CameraLookMouse;
    private readonly InputAction m_PlayerMovement_LockMouse;
    private readonly InputAction m_PlayerMovement_PlayerMove;
    private readonly InputAction m_PlayerMovement_RunModifier;
    private readonly InputAction m_PlayerMovement_RunToggle;
    private readonly InputAction m_PlayerMovement_CrawlModifier;
    private readonly InputAction m_PlayerMovement_CrawlToggle;
    private readonly InputAction m_PlayerMovement_CameraLookVR;
    private readonly InputAction m_PlayerMovement_CameraMoveVR;
    private readonly InputAction m_PlayerMovement_ResetVR;
    private readonly InputAction m_PlayerMovement_RightHandPosVR;
    private readonly InputAction m_PlayerMovement_RightHandRotVR;
    private readonly InputAction m_PlayerMovement_LeftHandPosVR;
    private readonly InputAction m_PlayerMovement_LeftHandRotVR;
    private readonly InputAction m_PlayerMovement_FireGun;
    private readonly InputAction m_PlayerMovement_PlaceFlag;
    private readonly InputAction m_PlayerMovement_PlaceWall;
    private readonly InputAction m_PlayerMovement_EscapeMonster;
    public struct PlayerMovementActions
    {
        private @ControlMap m_Wrapper;
        public PlayerMovementActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraLook => m_Wrapper.m_PlayerMovement_CameraLook;
        public InputAction @CameraLookMouse => m_Wrapper.m_PlayerMovement_CameraLookMouse;
        public InputAction @LockMouse => m_Wrapper.m_PlayerMovement_LockMouse;
        public InputAction @PlayerMove => m_Wrapper.m_PlayerMovement_PlayerMove;
        public InputAction @RunModifier => m_Wrapper.m_PlayerMovement_RunModifier;
        public InputAction @RunToggle => m_Wrapper.m_PlayerMovement_RunToggle;
        public InputAction @CrawlModifier => m_Wrapper.m_PlayerMovement_CrawlModifier;
        public InputAction @CrawlToggle => m_Wrapper.m_PlayerMovement_CrawlToggle;
        public InputAction @CameraLookVR => m_Wrapper.m_PlayerMovement_CameraLookVR;
        public InputAction @CameraMoveVR => m_Wrapper.m_PlayerMovement_CameraMoveVR;
        public InputAction @ResetVR => m_Wrapper.m_PlayerMovement_ResetVR;
        public InputAction @RightHandPosVR => m_Wrapper.m_PlayerMovement_RightHandPosVR;
        public InputAction @RightHandRotVR => m_Wrapper.m_PlayerMovement_RightHandRotVR;
        public InputAction @LeftHandPosVR => m_Wrapper.m_PlayerMovement_LeftHandPosVR;
        public InputAction @LeftHandRotVR => m_Wrapper.m_PlayerMovement_LeftHandRotVR;
        public InputAction @FireGun => m_Wrapper.m_PlayerMovement_FireGun;
        public InputAction @PlaceFlag => m_Wrapper.m_PlayerMovement_PlaceFlag;
        public InputAction @PlaceWall => m_Wrapper.m_PlayerMovement_PlaceWall;
        public InputAction @EscapeMonster => m_Wrapper.m_PlayerMovement_EscapeMonster;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMovementActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Add(instance);
            @CameraLook.started += instance.OnCameraLook;
            @CameraLook.performed += instance.OnCameraLook;
            @CameraLook.canceled += instance.OnCameraLook;
            @CameraLookMouse.started += instance.OnCameraLookMouse;
            @CameraLookMouse.performed += instance.OnCameraLookMouse;
            @CameraLookMouse.canceled += instance.OnCameraLookMouse;
            @LockMouse.started += instance.OnLockMouse;
            @LockMouse.performed += instance.OnLockMouse;
            @LockMouse.canceled += instance.OnLockMouse;
            @PlayerMove.started += instance.OnPlayerMove;
            @PlayerMove.performed += instance.OnPlayerMove;
            @PlayerMove.canceled += instance.OnPlayerMove;
            @RunModifier.started += instance.OnRunModifier;
            @RunModifier.performed += instance.OnRunModifier;
            @RunModifier.canceled += instance.OnRunModifier;
            @RunToggle.started += instance.OnRunToggle;
            @RunToggle.performed += instance.OnRunToggle;
            @RunToggle.canceled += instance.OnRunToggle;
            @CrawlModifier.started += instance.OnCrawlModifier;
            @CrawlModifier.performed += instance.OnCrawlModifier;
            @CrawlModifier.canceled += instance.OnCrawlModifier;
            @CrawlToggle.started += instance.OnCrawlToggle;
            @CrawlToggle.performed += instance.OnCrawlToggle;
            @CrawlToggle.canceled += instance.OnCrawlToggle;
            @CameraLookVR.started += instance.OnCameraLookVR;
            @CameraLookVR.performed += instance.OnCameraLookVR;
            @CameraLookVR.canceled += instance.OnCameraLookVR;
            @CameraMoveVR.started += instance.OnCameraMoveVR;
            @CameraMoveVR.performed += instance.OnCameraMoveVR;
            @CameraMoveVR.canceled += instance.OnCameraMoveVR;
            @ResetVR.started += instance.OnResetVR;
            @ResetVR.performed += instance.OnResetVR;
            @ResetVR.canceled += instance.OnResetVR;
            @RightHandPosVR.started += instance.OnRightHandPosVR;
            @RightHandPosVR.performed += instance.OnRightHandPosVR;
            @RightHandPosVR.canceled += instance.OnRightHandPosVR;
            @RightHandRotVR.started += instance.OnRightHandRotVR;
            @RightHandRotVR.performed += instance.OnRightHandRotVR;
            @RightHandRotVR.canceled += instance.OnRightHandRotVR;
            @LeftHandPosVR.started += instance.OnLeftHandPosVR;
            @LeftHandPosVR.performed += instance.OnLeftHandPosVR;
            @LeftHandPosVR.canceled += instance.OnLeftHandPosVR;
            @LeftHandRotVR.started += instance.OnLeftHandRotVR;
            @LeftHandRotVR.performed += instance.OnLeftHandRotVR;
            @LeftHandRotVR.canceled += instance.OnLeftHandRotVR;
            @FireGun.started += instance.OnFireGun;
            @FireGun.performed += instance.OnFireGun;
            @FireGun.canceled += instance.OnFireGun;
            @PlaceFlag.started += instance.OnPlaceFlag;
            @PlaceFlag.performed += instance.OnPlaceFlag;
            @PlaceFlag.canceled += instance.OnPlaceFlag;
            @PlaceWall.started += instance.OnPlaceWall;
            @PlaceWall.performed += instance.OnPlaceWall;
            @PlaceWall.canceled += instance.OnPlaceWall;
            @EscapeMonster.started += instance.OnEscapeMonster;
            @EscapeMonster.performed += instance.OnEscapeMonster;
            @EscapeMonster.canceled += instance.OnEscapeMonster;
        }

        private void UnregisterCallbacks(IPlayerMovementActions instance)
        {
            @CameraLook.started -= instance.OnCameraLook;
            @CameraLook.performed -= instance.OnCameraLook;
            @CameraLook.canceled -= instance.OnCameraLook;
            @CameraLookMouse.started -= instance.OnCameraLookMouse;
            @CameraLookMouse.performed -= instance.OnCameraLookMouse;
            @CameraLookMouse.canceled -= instance.OnCameraLookMouse;
            @LockMouse.started -= instance.OnLockMouse;
            @LockMouse.performed -= instance.OnLockMouse;
            @LockMouse.canceled -= instance.OnLockMouse;
            @PlayerMove.started -= instance.OnPlayerMove;
            @PlayerMove.performed -= instance.OnPlayerMove;
            @PlayerMove.canceled -= instance.OnPlayerMove;
            @RunModifier.started -= instance.OnRunModifier;
            @RunModifier.performed -= instance.OnRunModifier;
            @RunModifier.canceled -= instance.OnRunModifier;
            @RunToggle.started -= instance.OnRunToggle;
            @RunToggle.performed -= instance.OnRunToggle;
            @RunToggle.canceled -= instance.OnRunToggle;
            @CrawlModifier.started -= instance.OnCrawlModifier;
            @CrawlModifier.performed -= instance.OnCrawlModifier;
            @CrawlModifier.canceled -= instance.OnCrawlModifier;
            @CrawlToggle.started -= instance.OnCrawlToggle;
            @CrawlToggle.performed -= instance.OnCrawlToggle;
            @CrawlToggle.canceled -= instance.OnCrawlToggle;
            @CameraLookVR.started -= instance.OnCameraLookVR;
            @CameraLookVR.performed -= instance.OnCameraLookVR;
            @CameraLookVR.canceled -= instance.OnCameraLookVR;
            @CameraMoveVR.started -= instance.OnCameraMoveVR;
            @CameraMoveVR.performed -= instance.OnCameraMoveVR;
            @CameraMoveVR.canceled -= instance.OnCameraMoveVR;
            @ResetVR.started -= instance.OnResetVR;
            @ResetVR.performed -= instance.OnResetVR;
            @ResetVR.canceled -= instance.OnResetVR;
            @RightHandPosVR.started -= instance.OnRightHandPosVR;
            @RightHandPosVR.performed -= instance.OnRightHandPosVR;
            @RightHandPosVR.canceled -= instance.OnRightHandPosVR;
            @RightHandRotVR.started -= instance.OnRightHandRotVR;
            @RightHandRotVR.performed -= instance.OnRightHandRotVR;
            @RightHandRotVR.canceled -= instance.OnRightHandRotVR;
            @LeftHandPosVR.started -= instance.OnLeftHandPosVR;
            @LeftHandPosVR.performed -= instance.OnLeftHandPosVR;
            @LeftHandPosVR.canceled -= instance.OnLeftHandPosVR;
            @LeftHandRotVR.started -= instance.OnLeftHandRotVR;
            @LeftHandRotVR.performed -= instance.OnLeftHandRotVR;
            @LeftHandRotVR.canceled -= instance.OnLeftHandRotVR;
            @FireGun.started -= instance.OnFireGun;
            @FireGun.performed -= instance.OnFireGun;
            @FireGun.canceled -= instance.OnFireGun;
            @PlaceFlag.started -= instance.OnPlaceFlag;
            @PlaceFlag.performed -= instance.OnPlaceFlag;
            @PlaceFlag.canceled -= instance.OnPlaceFlag;
            @PlaceWall.started -= instance.OnPlaceWall;
            @PlaceWall.performed -= instance.OnPlaceWall;
            @PlaceWall.canceled -= instance.OnPlaceWall;
            @EscapeMonster.started -= instance.OnEscapeMonster;
            @EscapeMonster.performed -= instance.OnEscapeMonster;
            @EscapeMonster.canceled -= instance.OnEscapeMonster;
        }

        public void RemoveCallbacks(IPlayerMovementActions instance)
        {
            if (m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMovementActions @PlayerMovement => new PlayerMovementActions(this);

    // LevelControl
    private readonly InputActionMap m_LevelControl;
    private List<ILevelControlActions> m_LevelControlActionsCallbackInterfaces = new List<ILevelControlActions>();
    private readonly InputAction m_LevelControl_NextLevel;
    private readonly InputAction m_LevelControl_PreviousLevel;
    private readonly InputAction m_LevelControl_Pause;
    private readonly InputAction m_LevelControl_UnlockMouse;
    public struct LevelControlActions
    {
        private @ControlMap m_Wrapper;
        public LevelControlActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextLevel => m_Wrapper.m_LevelControl_NextLevel;
        public InputAction @PreviousLevel => m_Wrapper.m_LevelControl_PreviousLevel;
        public InputAction @Pause => m_Wrapper.m_LevelControl_Pause;
        public InputAction @UnlockMouse => m_Wrapper.m_LevelControl_UnlockMouse;
        public InputActionMap Get() { return m_Wrapper.m_LevelControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LevelControlActions set) { return set.Get(); }
        public void AddCallbacks(ILevelControlActions instance)
        {
            if (instance == null || m_Wrapper.m_LevelControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LevelControlActionsCallbackInterfaces.Add(instance);
            @NextLevel.started += instance.OnNextLevel;
            @NextLevel.performed += instance.OnNextLevel;
            @NextLevel.canceled += instance.OnNextLevel;
            @PreviousLevel.started += instance.OnPreviousLevel;
            @PreviousLevel.performed += instance.OnPreviousLevel;
            @PreviousLevel.canceled += instance.OnPreviousLevel;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @UnlockMouse.started += instance.OnUnlockMouse;
            @UnlockMouse.performed += instance.OnUnlockMouse;
            @UnlockMouse.canceled += instance.OnUnlockMouse;
        }

        private void UnregisterCallbacks(ILevelControlActions instance)
        {
            @NextLevel.started -= instance.OnNextLevel;
            @NextLevel.performed -= instance.OnNextLevel;
            @NextLevel.canceled -= instance.OnNextLevel;
            @PreviousLevel.started -= instance.OnPreviousLevel;
            @PreviousLevel.performed -= instance.OnPreviousLevel;
            @PreviousLevel.canceled -= instance.OnPreviousLevel;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @UnlockMouse.started -= instance.OnUnlockMouse;
            @UnlockMouse.performed -= instance.OnUnlockMouse;
            @UnlockMouse.canceled -= instance.OnUnlockMouse;
        }

        public void RemoveCallbacks(ILevelControlActions instance)
        {
            if (m_Wrapper.m_LevelControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILevelControlActions instance)
        {
            foreach (var item in m_Wrapper.m_LevelControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LevelControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LevelControlActions @LevelControl => new LevelControlActions(this);

    // UIControl
    private readonly InputActionMap m_UIControl;
    private List<IUIControlActions> m_UIControlActionsCallbackInterfaces = new List<IUIControlActions>();
    private readonly InputAction m_UIControl_ToggleCompass;
    private readonly InputAction m_UIControl_ToggleStats;
    private readonly InputAction m_UIControl_ToggleMap;
    public struct UIControlActions
    {
        private @ControlMap m_Wrapper;
        public UIControlActions(@ControlMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleCompass => m_Wrapper.m_UIControl_ToggleCompass;
        public InputAction @ToggleStats => m_Wrapper.m_UIControl_ToggleStats;
        public InputAction @ToggleMap => m_Wrapper.m_UIControl_ToggleMap;
        public InputActionMap Get() { return m_Wrapper.m_UIControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIControlActions set) { return set.Get(); }
        public void AddCallbacks(IUIControlActions instance)
        {
            if (instance == null || m_Wrapper.m_UIControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIControlActionsCallbackInterfaces.Add(instance);
            @ToggleCompass.started += instance.OnToggleCompass;
            @ToggleCompass.performed += instance.OnToggleCompass;
            @ToggleCompass.canceled += instance.OnToggleCompass;
            @ToggleStats.started += instance.OnToggleStats;
            @ToggleStats.performed += instance.OnToggleStats;
            @ToggleStats.canceled += instance.OnToggleStats;
            @ToggleMap.started += instance.OnToggleMap;
            @ToggleMap.performed += instance.OnToggleMap;
            @ToggleMap.canceled += instance.OnToggleMap;
        }

        private void UnregisterCallbacks(IUIControlActions instance)
        {
            @ToggleCompass.started -= instance.OnToggleCompass;
            @ToggleCompass.performed -= instance.OnToggleCompass;
            @ToggleCompass.canceled -= instance.OnToggleCompass;
            @ToggleStats.started -= instance.OnToggleStats;
            @ToggleStats.performed -= instance.OnToggleStats;
            @ToggleStats.canceled -= instance.OnToggleStats;
            @ToggleMap.started -= instance.OnToggleMap;
            @ToggleMap.performed -= instance.OnToggleMap;
            @ToggleMap.canceled -= instance.OnToggleMap;
        }

        public void RemoveCallbacks(IUIControlActions instance)
        {
            if (m_Wrapper.m_UIControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIControlActions instance)
        {
            foreach (var item in m_Wrapper.m_UIControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIControlActions @UIControl => new UIControlActions(this);
    public interface IPlayerMovementActions
    {
        void OnCameraLook(InputAction.CallbackContext context);
        void OnCameraLookMouse(InputAction.CallbackContext context);
        void OnLockMouse(InputAction.CallbackContext context);
        void OnPlayerMove(InputAction.CallbackContext context);
        void OnRunModifier(InputAction.CallbackContext context);
        void OnRunToggle(InputAction.CallbackContext context);
        void OnCrawlModifier(InputAction.CallbackContext context);
        void OnCrawlToggle(InputAction.CallbackContext context);
        void OnCameraLookVR(InputAction.CallbackContext context);
        void OnCameraMoveVR(InputAction.CallbackContext context);
        void OnResetVR(InputAction.CallbackContext context);
        void OnRightHandPosVR(InputAction.CallbackContext context);
        void OnRightHandRotVR(InputAction.CallbackContext context);
        void OnLeftHandPosVR(InputAction.CallbackContext context);
        void OnLeftHandRotVR(InputAction.CallbackContext context);
        void OnFireGun(InputAction.CallbackContext context);
        void OnPlaceFlag(InputAction.CallbackContext context);
        void OnPlaceWall(InputAction.CallbackContext context);
        void OnEscapeMonster(InputAction.CallbackContext context);
    }
    public interface ILevelControlActions
    {
        void OnNextLevel(InputAction.CallbackContext context);
        void OnPreviousLevel(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnUnlockMouse(InputAction.CallbackContext context);
    }
    public interface IUIControlActions
    {
        void OnToggleCompass(InputAction.CallbackContext context);
        void OnToggleStats(InputAction.CallbackContext context);
        void OnToggleMap(InputAction.CallbackContext context);
    }
}
